theme: jekyll-theme-minimal

# Analytics
analytics:
  provider               : "google-universal" # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "G-ETJHLSQQ91" # Replace this with your ID, or delete
    anonymize_ip         : true 
    
title: XCast
logo: XCastLogo.png
description: A High-Performance Data Science Toolkit for the Earth Sciences
