theme: jekyll-theme-minimal
google_analytics: G-ETJHLSQQ91
plugins: 
  - jekyll-seo-tag
 
image:
  path: social.png

title: XCast
logo: XCastLogo.png
description: A High-Performance Data Science Toolkit for the Earth Sciences
