theme: jekyll-theme-minimal
google_analytics: "G-ETJHLSQQ91" # Replace this with your ID, or delete    
title: XCast
logo: XCastLogo.png
description: A High-Performance Data Science Toolkit for the Earth Sciences
