package:
  name: xcast
  version: "0.1.0"

source:
  path:  ..
build:
  number: 0
  string: xcast


requirements:
  host:
    - python>=3.4,<3.9
    - pip
    - setuptools
  run:
    - python>=3.4,<3.9
    - numpy
    - scipy
    - scikit-learn
    - extremelearning
    - xarray
    - dask
    - cartopy
    - matplotlib
    - pathlib
    - h5py
    - statsmodels
    - opencv
    - xskillscore



test:
  imports:
    - xcast
    - xcast.core
    - xcast.mme
    - xcast.preprocessing
    - xcast.validation
    - xcast.verification
about:
  home:
  license: MIT
  summary: 'A Gridpoint-Wise Statistical and Machine Learning library for the Earth Sciences'
  description: 'High-Performance Gridpoint-Wise Machine Learning for the Earth Sciences'
  dev_url:  https://github.com/kjhall01/xcast/
