package:
  name: xcast
  version: "0.5.0"

source:
  #url: https://github.com/kjhall01/xcast/archive/refs/tags/v0.4.1.tar.gz
  path: ../src
build:
  number: 0
  string: xcast

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - numpy
    - scipy
    - scikit-learn
    - xarray
    - dask
    - matplotlib
    - pathlib
    - statsmodels
    - opencv

test:
  imports:
    - xcast
    - xcast.classification
    - xcast.core
    - xcast.flat_estimators
    - xcast.flat_estimators.classifiers
    - xcast.flat_estimators.regressors
    - xcast.preprocessing
    - xcast.regression
    - xcast.validation
    - xcast.verification
about:
  home:
  license: MIT
  summary: "A Gridpoint-Wise Statistical and Machine Learning library for the Earth Sciences"
  description: "High-Performance Gridpoint-Wise Machine Learning for the Earth Sciences"
  dev_url: https://github.com/kjhall01/xcast/
